baseURL = 'https://edibleloughborough.org.uk/'
languageCode = 'en-gb'
title = 'Incredible Edible Loughborough'
disableKinds = ['taxonomy', 'term']
ignoreLogs = ['warning-goldmark-raw-html']

[params]
  shortTitle = "IEL"
  contactEmailAddress = "info@edibleloughborough.org.uk"

[menu]
  [[menu.main]]
    name = 'Home'
    url = '/'
    weight = 1
  [[menu.main]]
    name = 'Our Gardens'
    url = '/our-gardens/'
    weight = 2
  [[menu.main]]
    name = 'Contact Us'
    url = '/contact-us/'
    weight = 3